### ISSUE TITLE
error absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --preserve_unused_tokens before flags were parsed.

### ISSUE THREAD

**Issue by seojong789** [jouniluoma/keras-bert-ner#6]
Hello, I'm running in colab.

!sudo chmod -R 755 ./scripts/run-turku-ner.sh
!sudo chmod -R 755 ./scripts/predict-turku-ner.sh
!./scripts/run-turku-ner.sh
!./scripts/predict-turku-ner.sh

![1](https://user-images.githubusercontent.com/74905388/99952612-4128d600-2dc3-11eb-89e4-3541a2a41e3b.gif)

I need your help with this error. plz..

**Comment by jouniluoma** [comment]
Hi, this seems to be raised from bert tokenization implementation and there are similar errors reported e.g. in https://github.com/google-research/bert/issues/1133

I think it is due bert / tensorflow / keras-bert version mismatch.

I am just about to release a bit newer code on https://github.com/jouniluoma/bert-ner-cmv with some enhancements. I have taken the bert tokenizer and modified one line there for it to be compatible with tf2. I guess that could help.

**Comment by seojong789** [comment]
Your kindness really helped me.
Thank you again. Thank you very much.
