### ISSUE TITLE
Dataset format..

### ISSUE THREAD

**Issue by seojong789** [jouniluoma/keras-bert-ner#7]
The last reply was very helpful. i'm so so thank you
Excuse me, is there a way to use WWW dataset?
I need the format code of finer to use WWW dataset.
The expression might be weird because I'm using Papago. I apologize for this.

**Comment by seojong789** [comment]
![12](https://user-images.githubusercontent.com/74905388/100206831-2cc31580-2f4a-11eb-8eb6-f40896d06f6a.GIF)

**Comment by jouniluoma** [comment]
OK, I am not completely sure what you want to achieve, but here are some thoughts.

- If you want to use a trained model on text it is perhaps best to check a fork of this repo https://github.com/spyysalo/keras-bert-ner with better support as using the model as server.
- If you have an annotated dataset in other format than the one used here (tab separated word + class), you should convert the format of that dataset. This implementation does not support other file formats as I made this mainly for research purposes, not as ready to use software.

I hope these will help!
